### ISSUE TITLE
Has many through , attributes not working

### ISSUE THREAD

**Issue by anand9** [moiristo/deep_cloneable#49]
I have my associations as

``` 
Report
       has_many :projects
       has_many :project_milestones, through: :projects
       has_many :members, through: :projects

        accepts_nested_attributes_for :key_activities , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :risks , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :projects , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :project_milestones , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :members , :reject_if => :all_blank, :allow_destroy => true

```

and i try to deep clone 

``` 
r = Report.last.deep_clone :include => [:key_activities, :risks, {:projects => [:project_milestones, :members]}]
```

i am getting all attributes except project_milestones and members

```
r.projects.last.members.last
=> #<Member:0x007f8234394ed8 id: nil, name: "", worked_hrs: "", created_at: nil, updated_at: nil, project_id: nil>
```
what could be wrong here? :o

**Comment by moiristo** [comment]
At first sight it doesn't look like this issue is caused by deep_cloneable. The code eventually calls 'dup()' on the record, which should copy the member attributes. It might of course be related to your environment (ruby/rails version). Could you provide a failing test? The current test for hm-through is defined here: https://github.com/moiristo/deep_cloneable/blob/master/test/test_deep_cloneable.rb#L322.

**Comment by anand9** [comment]
Sorry it was an error with my code. Its working like a charm
Thanks a lot
